# Generated by Django 3.0.7 on 2020-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.CharField(max_length=200)),
                ('Colour', models.CharField(max_length=200)),
                ('Position', models.IntegerField(default=0)),
                ('DateCreated', models.DateTimeField(verbose_name='date created')),
                ('DateLastUpdated', models.DateTimeField(verbose_name='date last updated')),
            ],
        ),
    ]
